In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
no_of_units = np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_unit = np.array([1000,400,1200])

In [9]:
total_sale = np.dot(price_per_unit,no_of_units)
total_sale

array([[34400, 50000, 64400]])

In [11]:
revenue_dollar = np.array([[200,220,250],[68, 79, 105],[110,140,180],[80,85,90]])
inr_price = 75

In [12]:
converting_price = revenue_dollar * inr_price
converting_price

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])