In [24]:
import tensorflow as tf
import numpy as np
import math

    

In [30]:
import tensorflow as tf

input_values = tf.constant([100, 1, -5, -30], dtype=tf.float32)
sigmoid_func = tf.math.sigmoid(input_values)

print(sigmoid_func.numpy())

#    or 

def sigmoid(x):
    return 1/(1 + math.exp(-x))

[1.0000000e+00 7.3105854e-01 6.6928524e-03 9.3576243e-14]


In [2]:
sigmoid(100)

1.0

In [3]:
sigmoid(1)

0.7310585786300049

### Tanh

In [14]:

input_tensor =([-56.0,50.0,1.0])
tanh_func = tf.math.tanh(input_tensor)
tanh_func.numpy()

array([-1.       ,  1.       ,  0.7615942], dtype=float32)

### Relu

In [16]:
input_values = ([-4, 10, -18, 40])
relu_func = tf.nn.relu(input_values)
relu_func.numpy()

array([ 0, 10,  0, 40], dtype=int32)

### Leaky Relu

In [31]:
def leaky_relu(x):
    return max(0.1*x,x)


In [32]:
leaky_relu(-100)

-10.0

In [37]:
leaky_relu(-10)

-1.0